export const useConfig = () => {
    return {
        NOTES_PER_PAGE: 20,
        RECOMMENDED_CLIENTS: [
            {
                name: "Megalodon",
                icon: "https://sk22.github.io/megalodon/mastodon/src/main/res/mipmap-xhdpi/ic_launcher_round.png",
                link: "https://sk22.github.io/megalodon/",
            },
        ],
        COMPOSER_SPLASHES: [
            "What's on your mind?",
            "What's happening?",
            "Meow meow meow meow meow",
            "Just arrived at Luna Nova Academy",
            "I'm a little teapot, short and stout",
            "Hey, you. You're finally awake. You were trying to cross the border, right?",
            "Aren't you a little short for a stormtrooper?",
            "I'm a leaf on the wind. Watch how I soar.",
            "I am Groot.",
            "Hello everybody, my name is Markiplier",
            "I'm Commander Shepard, and this is my favorite website on the Citadel",
            "I'm sorry, Dave. I'm afraid I can't do that.",
            "I am the Senate",
            "Check out my geek code!",
            "You've got mail!",
            "Dude, Where's My Potato?",
            "eau de potato",
            "The bee's knees!",
            "12 herbs and spices!",
            "Ceci n'est pas une post!",
            "sqrt(-1) love you!",
            "Cthulhu is mad... and is missing an eye!",
            "Versia: Build on blackbox technology!",
            "A goblin army is approaching from the west!",
            "git gud!",
            "Must have been the wind..",
            "I am the milkman, my milk is delicious.",
            "It's not out of the question, that you might have a very minor case, of serious brain damage",
            "I died",
            "Remember, switching to your secondary is faster than reloading!",
            "Everybody in america is a female.",
            "I am going to test in production",
            "War... war never changes.",
            "Fedi... fedi never changes.",
            "Finish him!",
            "The dopamine is a lie.",
            "I'll be back.",
            "My name is Guybrush Threepwood, and I want to be a pirate!",
            "It's dangerous to post alone! Take this.",
            "I used to be an poster like you, then I took an arrow to the knee.",
            "All your post are belong to us.",
            "I'm here to shitpost and chew bubblegum... and I'm all outta gum.",
            "Houston, we have a problem.",
            "Clever girl.",
            "Wibbly wobbly, timey wimey... stuff.",
            "Bow ties are cool.",
            "I'm the Doctor, and you're probably not.",
            "I'm a madman with a box.",
            "Geronimo!",
            "It's bigger on the inside!",
            "I'm going to make him an offer he can't refuse.",
            "Hello there.",
            "I'll post what she's posting.",
            "To infinity... and beyond!",
            "E.T. phone home.",
            "Just keep posting!",
            "Just one more post bro",
        ],
        DEVELOPER_HANDLES: [
            "jessew@social.lysand.org",
            "jessew@beta.versia.social",
            "jessew@versia.social",
            "jessew@vs.cpluspatch.com",
            "aprl@social.lysand.org",
            "aprl@beta.versia.social",
            "aprl@versia.social",
            "graphite@social.lysand.org",
            "jessew@mk.cpluspatch.com",
            "graphite@shonk.phite.ro",
        ],
    };
};
